<?php

ClassLoader::import("framework.response.RawResponse");

/**
 * Response with output buffering
 * 
 * Use this type of response when you need "to catch" an output generated by some 3rd 
 * party libraries because such an output would cause a HeadersSentException
 * 
 * <code>
 * $response = new RawResponse();
 * 
 * // Starting OB
 * $response->start();
 * 
 * echo "Here goes some uncontrolled output"
 * 
 * // Ending OB and storing "catched" output as response content
 * $response->end();
 * return $response;
 * 
 * </code>
 * 
 * @link http://lt.php.net/manual/en/ref.outcontrol.php
 * @package framework.response
 */
class OBResponse extends RawResponse {
	
	const AUTO_START = true;
	
	/**
	 * Creates a response with output buffering
	 *
	 * @param bool $autoStartOB If true starts output buffering automatically
	 */
	public function __construct($autoStartOB = true) {
		if ($autoStartOB) {
			$this->start();
		}
	}
	
	/**
	 * Alias for self:end() method.
	 *
	 */
	public function storeData() {
		$this->end();
	}
	
	/**
	 * Starts output buffering
	 *
	 */
	public function start() {
		ob_start();
	}
	
	/**
	 * Ends output buffering and stores gathered data as response
	 *
	 */
	public function end() {
		$data = ob_get_contents();
		ob_clean();
		$this->setContent($data);
	}
}

?>